######服务器设置######
server:
  port: 8080 #启动内嵌tomcat，设置其端口号
  contextPath: /core #项目在tomcat中的contextPath
  session:
    timeout: 36000

######Spring设置######
spring:
  aop:
    auto: true
  http:
    encoding:
        charset: UTF-8
        enabled: true
        force: true
  datasource:
    url: jdbc:mysql://172.24.7.226:3306/jdquant?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1qaz2wsx
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 0
# Redis服务器地址
    host: 192.168.99.100
# Redis服务器连接端口
    port: 32769
# Redis服务器连接密码（默认为空）
    password:
# 连接超时时间（毫秒）
    timeout: 0
# 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
# 连接池中的最大空闲连接
      max-idle: 8
# 连接池中的最小空闲连接
      min-idle: 1

  session:
    store-type: redis

######日志设置######
logging:
  path: /export/Logs/jdquant/ #日志文件目录
  file: ${logging.path}quant-core.log
  level: debug

######Thrift设置######
thrift:
  serverPort: 22006
  protocol: compact
