# Spring Profiles Active
spring:
  mvc:
    static-path-pattern: /static/**
  profiles:
    active: develop  #根据环境改变

# Banner Setting
banner:
  location: static/banner.txt

# Mybatis Config
mybatis:
  mapperLocations: classpath*:mappers/*.xml
  type-aliases-package: com.jd.quant.core.domain
  executor-type: batch